- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create the docker image
    command: docker build -t project1:CICD .
    args:
      chdir: /var/lib/jenkins/workspace/1.ContinuousIntegration/website


  - name: Log into DockerHub
    docker_login:
     username: kubedas
     password: #Qwe1234

  
  - name: Tag and push to docker hub
    docker_image:
     name: project1
     repository: kubedas/project1 
     tag: CICD
     push: yes


  - name: remove docker images form ansible server
    command: docker rmi -f kubedas/project1:CICD project1
    ignore_errors: yes
