- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create the docker image
    command: docker build -t EdurekaProject1:CICD .
    args:
      chdir: /var/lib/jenkins/workspace/1.ContinuousIntegration/website

  - name: create tag to image
    command: docker tag EdurekaProject1:CICD ssdocs/EdurekaProject1:CICD

  - name: login to docker
    command: docker login --username ssdocs  --password #Qwe1234asd

  - name: push image on to dockerhub
    command: docker push ssdocs/EdurekaProject1:CICD

  - name: remove docker images form ansible server
    command: docker rmi EdurekaProject1:CICD ssdocs/EdurekaProject1:CICD
    ignore_errors: yes
